kind: Deployment
apiVersion: apps/v1
metadata:
  name: workflowui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflowui
  template:
    metadata:
      labels:
        app: workflowui
    spec:
      containers:
        - name: workflowui
          image: localhost:5000/workflowui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: workflowui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: workflowui