kind: Deployment
apiVersion: apps/v1
metadata:
  name: graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: localhost:5000/graphql
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
    service: graphql
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: graphql